# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_a', models.BigIntegerField()),
                ('data_b', models.BigIntegerField()),
                ('data_c', models.BigIntegerField()),
                ('data_d', models.BigIntegerField()),
                ('data_e', models.BigIntegerField()),
                ('data_f', models.BigIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
